language: erlang
notifications:
  recipients:
    - tanzi.marco@gmail.com
otp_release:
  - 17.0
env:
  ELIXIR=v1.0.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - "export PATH=`pwd`/elixir/bin:$PATH"
  - mix local.hex --force
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
